language: php
php:
- '5.6'
- '5.5'
notifications:
  email: false
install:
  - composer install --dev --no-scripts
script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - vendor/bin/test-reporter
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: keboola:atHihCm3qSPtAy0EowLA5WjD
addons:
  code_climate:
    repo_token:
      secure: ""